spring:
  datasource:
    platform: h2
    url: jdbc:h2:mem:soccer;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    name: soccer
  h2:
    console:
      path: /h2
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    show-sql: true